### ISSUE TITLE
Parallel population transfer code

### ISSUE THREAD

**Issue by GHlacour** [lacourjansenlab/NISE_2017#19]
**Is your feature request related to a problem? Please describe.**
The current code for population transfer (Pop) is not running parallel limiting the use on for example Snellius.

**Describe the solution you'd like**
With openMP it should be easy to distribute the propagation of different vectors (indexed by a) to different cores. These parts are essentially independent.

**Describe alternatives you've considered**
MPI would be possible too, but this is more cumbersome and probably not needed.

**Additional context**
Vesna would like to use this part of the code for her large system

**Comment by vjesnO** [comment]
I created a new branch called population_transfer and I will try to make some parts of the code OpenMP parallel.

**Comment by GHlacour** [comment]
This was successfully implemented and added to a number of other techniques as well.
